pipeline{
 agent any
 stages {
        stage('build') {
            steps{
                echo 'build'
                sh "docker build -t flaskr examples/"
            }
        }
        stage('push') {
            steps{
                sh "docker save flaskr > examples/flaskr.tar"
                sh 'ansible-playbook -i examples/ansible_hosts examples/flaskapp.yml'
            }
        }
    }
 post {
     always {
        echo 'end'
     }
 }
}

1.
centos5 6  iptables
7 8  firewalld  iptables  netfilter

2. secure syslog  acceslog  lastb 
3. radius nginx 

redhat 
selinux 

solaris ufw ? 